[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
[tool.setuptools.packages.find]
include = ["pareft*"]
name = "pareft"
version = "0.1.0"
description = "Programmable Axidilaton Resonant EFT research scaffold"
authors = [{name="Anulum Institute", email="info@anulum.example"}]
requires-python = ">=3.10"
dependencies = [
  "numpy>=1.24",
  "scipy>=1.11",
  "pyyaml>=6.0",
  "matplotlib>=3.7",
]