name: demo-artifacts

on:
  workflow_dispatch:    # ručné spustenie z Actions tab
  push:
    branches: [ main ]  # spúšťaj na push do main
    paths:
      - 'pareft/**'
      - 'configs/**'
      - 'pyproject.toml'
      - '.github/workflows/demo-artifacts.yml'
      - 'README.md'

jobs:
  demo:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      MPLBACKEND: Agg     # headless matplotlib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run demo
        run: |
          # Rýchly demo beh (použijeme existujúci príklad)
          pareft configs/example.yaml \
            --triplet C2,C3,C6 \
            --durations 5,10,5 \
            --save-raw 1 \
            --save-plots 1
          echo "== ls outputs/example =="
          ls -la outputs/example || true

      - name: Upload artifacts (PNGs/CSVs/JSON)
        uses: actions/upload-artifact@v4
        with:
          name: pareft-demo-${{ github.run_id }}
          path: |
            outputs/example/*.csv
            outputs/example/*.png
            outputs/example/metadata.json
          if-no-files-found: error
          retention-days: 7
