name: demo-run
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run demo
        run: |
          pareft configs/example.yaml --triplet C2,C3,C6 --durations 10,40,10 --save-raw=1
          python scripts/analyze.py outputs/example

      - name: Upload PNG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-example-png
          path: |
            outputs/example/*.png
          if-no-files-found: error

      - name: Upload CSV+JSON (optional)
        uses: actions/upload-artifact@v4
        with:
          name: outputs-example-data
          path: |
            outputs/example/*.csv
            outputs/example/*.json
          if-no-files-found: warn
